INSERT INTO DISHES (NAME, PRICE, DISH_TYPE) VALUES ('TIKKA MASALA', 19.99, 'MEAT');
INSERT INTO DISHES (NAME, PRICE, DISH_TYPE) VALUES ('SCHABOWY Z ZIEMNIAKAMI I SURÓWKĄ', 13.99, 'MEAT');
INSERT INTO DISHES (NAME, PRICE, DISH_TYPE) VALUES ('WĘDZONE TOFU Z MAKARONEM RYŻOWYM', 11.99, 'VEGAN');
INSERT INTO DISHES (NAME, PRICE, DISH_TYPE) VALUES ('HUMMUS Z BAKŁAŻANEM', 10.99, 'VEGETARIAN');
INSERT INTO DISHES (NAME, PRICE, DISH_TYPE) VALUES ('RYŻ SMAŻONY Z KURCZAKIEM', 12.99, 'MEAT');
