
INSERT INTO USERS (login, password)

VALUES ('tester', 'e99a18c428cb38d5f260853678922e03');

INSERT INTO USERS (login, password)

VALUES ('Jeremi', 'e99a18c428cb38d5f260853678922e03');

INSERT INTO USERS (login, password)

VALUES ('Maćko', 'e99a18c428cb38d5f260853678922e03');


INSERT INTO CATERERS (NAME, ADDRESS, CUISINE, TELEPHONE, EMAIL)

VALUES ('PIZZA HUT', 'NIEPODLEGLOŚCI 135, WARSZAWA 04-570', 'ITALIAN', '2232353546', 'NIEPODLEGLOSCI@PIZZAHUT.PL');

INSERT INTO CATERERS (NAME, ADDRESS, CUISINE, TELEPHONE, EMAIL)

VALUES ('U BABUNI', 'RACŁAWICKA 15, WARSZAWA 02-570', 'POLISH', '2232656446', 'UBABUNI@O2.PL');


INSERT INTO DISHES (NAME, PRICE, DISH_TYPE, CATERERS_ID)

VALUES ('TIKKA MASALA', 19.99, 'MEAT', 1);

INSERT INTO DISHES (NAME, PRICE, DISH_TYPE, CATERERS_ID)

VALUES ('SCHABOWY Z ZIEMNIAKAMI I SURÓWKĄ', 13.99, 'MEAT', 2);

INSERT INTO DISHES (NAME, PRICE, DISH_TYPE, CATERERS_ID)

VALUES ('WĘDZONE TOFU Z MAKARONEM RYŻOWYM', 11.99, 'VEGAN', 1);

INSERT INTO DISHES (NAME, PRICE, DISH_TYPE, CATERERS_ID)

VALUES ('HUMMUS Z BAKŁAŻANEM', 10.99, 'VEGETARIAN', 2);

INSERT INTO DISHES (NAME, PRICE, DISH_TYPE, CATERERS_ID)

VALUES ('RYŻ SMAŻONY Z KURCZAKIEM', 12.99, 'MEAT', 1);


INSERT INTO TRANSACTIONS (CATERERs_ID, TRANSACTION_STATUS, TRANSACTION_DATE)
VALUES (1, 'IN_PREPARATION', '2019-03-20');

INSERT INTO TRANSACTIONS (CATERERs_ID, TRANSACTION_STATUS, TRANSACTION_DATE)
VALUES (2, 'IN_PREPARATION', '2019-03-20');

INSERT INTO TRANSACTIONS (CATERERs_ID, TRANSACTION_STATUS, TRANSACTION_DATE)
VALUES (1, 'IN_PREPARATION', '2019-03-21');


INSERT INTO orders(users_id, order_date, CATERERs_ID, transactions_id)

VALUES (1, '2019-03-16', 1, 1);

INSERT INTO orders(users_id, order_date, CATERERs_ID, transactions_id)

VALUES (1, '2019-03-17', 2, 1);

INSERT INTO orders(users_id, order_date, CATERERs_ID, transactions_id)

VALUES (1, '2019-03-18', 1, 2);

INSERT INTO orders(users_id, order_date, CATERERs_ID, transactions_id)

VALUES (2, '2019-03-21', 1, 2);

INSERT INTO orders(users_id, order_date, CATERERs_ID, transactions_id)

VALUES (3, '2019-03-21', 2, 2);


INSERT INTO order_items (dishes_id, orders_id)

values (1, 4);

INSERT INTO order_items (dishes_id, orders_id)

values (2, 4);

INSERT INTO order_items (dishes_id, orders_id)

values (3, 5);

INSERT INTO order_items (dishes_id, orders_id)

values (4, 6);

INSERT INTO order_items (dishes_id, orders_id)

values (5, 6);


INSERT INTO TRANSACTION_ITEMS (ORDERS_ID, TRANSACTIONS_ID)
VALUES (1, 1);

INSERT INTO TRANSACTION_ITEMS (ORDERS_ID, TRANSACTIONS_ID)
VALUES (2, 1);

INSERT INTO TRANSACTION_ITEMS (ORDERS_ID, TRANSACTIONS_ID)
VALUES (3, 2);